import {
  Aperture,
  ArrowDownLeft,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Award,
  BadgeCheck,
  Banknote,
  Bell,
  BellOff,
  Bookmark,
  Building2,
  Camera,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  CircleDollarSign,
  CirclePlus,
  Clock,
  Coffee,
  Compass,
  Copy,
  ExternalLink,
  Eye,
  EyeOff,
  FilePen,
  Flame,
  Fuel,
  Gauge,
  Gift,
  Globe,
  Hand,
  HandHeart,
  Heart,
  Hourglass,
  ImagePlus,
  Info,
  LayoutGrid,
  Mail,
  MapPin,
  Medal,
  Megaphone,
  MessageCircle,
  Palette,
  PartyPopper,
  Plus,
  RefreshCw,
  Rocket,
  Share2,
  Shield,
  ShieldCheck,
  SlidersHorizontal,
  Smile,
  Sparkles,
  Star,
  Sun,
  Sunrise,
  Tag,
  Timer,
  Trophy,
  User,
  UserPlus,
  Users,
  UtensilsCrossed,
  Video,
  Vote,
  Wallet,
  X,
  Zap,
  ZapOff,
  type LucideIcon as LucideIconType,
} from "lucide-react";

/**
 * Resolver for data-driven icon names (values that come from config objects or
 * mock/API data). Static call sites should import the lucide component directly.
 * Keys are the legacy Material Symbols names so existing data shapes keep working.
 */
const ICONS: Record<string, LucideIconType> = {
  account_balance_wallet: Wallet,
  add: Plus,
  add_a_photo: ImagePlus,
  add_circle: CirclePlus,
  add_circle_outline: CirclePlus,
  apps: LayoutGrid,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  arrow_outward: ArrowUpRight,
  auto_awesome: Sparkles,
  bolt: Zap,
  bookmark: Bookmark,
  bookmark_border: Bookmark,
  call_received: ArrowDownLeft,
  campaign: Megaphone,
  celebration: PartyPopper,
  check: Check,
  check_circle: CircleCheck,
  chevron_right: ChevronRight,
  close: X,
  content_copy: Copy,
  done: Check,
  done_all: CheckCheck,
  edit_note: FilePen,
  emoji_events: Trophy,
  error: CircleAlert,
  expand_more: ChevronDown,
  explore: Compass,
  favorite: Heart,
  flash_off: ZapOff,
  flash_on: Zap,
  group: Users,
  hourglass_top: Hourglass,
  how_to_vote: Vote,
  info: Info,
  ios_share: Share2,
  leaderboard: Trophy,
  local_cafe: Coffee,
  local_fire_department: Flame,
  local_gas_station: Fuel,
  location_city: Building2,
  location_on: MapPin,
  mail: Mail,
  military_tech: Medal,
  mode_comment: MessageCircle,
  monetization_on: CircleDollarSign,
  north_east: ArrowUpRight,
  notifications: Bell,
  notifications_none: BellOff,
  open_in_new: ExternalLink,
  palette: Palette,
  payments: Banknote,
  person: User,
  person_add: UserPlus,
  photo_camera: Camera,
  public: Globe,
  redeem: Gift,
  refresh: RefreshCw,
  restaurant: UtensilsCrossed,
  rocket_launch: Rocket,
  schedule: Clock,
  sentiment_very_satisfied: Smile,
  share: Share2,
  shield: Shield,
  shutter_speed: Aperture,
  south_west: ArrowDownLeft,
  speed: Gauge,
  stars: Star,
  sync: RefreshCw,
  tag: Tag,
  timer: Timer,
  tune: SlidersHorizontal,
  verified: BadgeCheck,
  verified_user: ShieldCheck,
  videocam: Video,
  visibility: Eye,
  visibility_off: EyeOff,
  volunteer_activism: HandHeart,
  waving_hand: Hand,
  wb_sunny: Sun,
  wb_twilight: Sunrise,
  whatshot: Flame,
  workspace_premium: Award,
};

type Props = {
  /** Legacy Material Symbols name, typically sourced from data/config. */
  name: string;
  size?: number;
  filled?: boolean;
  className?: string;
};

/**
 * Renders a lucide icon from a string name. Falls back to a neutral dot-free
 * placeholder (Info) if an unknown name slips through, so the UI never breaks.
 */
export function LucideIcon({ name, size = 20, filled, className }: Props) {
  const Cmp = ICONS[name] ?? Info;
  return <Cmp size={size} className={className} fill={filled ? "currentColor" : "none"} />;
}
