[profile.default]
src = "src"
out = "out"
test = "test"
script = "script"
libs = []
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
bsc_testnet = "${BLOCKCHAIN_RPC_URL}"

[etherscan]
bsc_testnet = { key = "${BSCSCAN_API_KEY}", url = "https://api-testnet.bscscan.com/api", chain = 97 }

